create table PACIENTE(
    SEQ_PACIENTE INT NOT NULL,
    NOME_PACIENTE VARCHAR2(200) NOT NULL,
    NOME_MAE VARCHAR2(200), 
    SEXO_PACIENTE VARCHAR2(20),
    CPF_PACIENTE VARCHAR2(20),
    DATA_NASCIMENTO varchar2(20),
    CONSTRAINT paciente_pk PRIMARY KEY (SEQ_PACIENTE,CPF_PACIENTE)
);

CREATE SEQUENCE SEQ_PACIENTE
START WITH 1000
INCREMENT BY 10
NOMAXVALUE
NOMINVALUE
NOCACHE
NOCYCLE;